BookReview/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books do
    resources :comments #only: [:create]
  end
  
  root 'books#index'  
end

BookReview/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

BookReview/app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :comments
end

BookReview/app/models/category.rb
class Category < ApplicationRecord
    has_many :books
end

BookReview/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates :content, presence: true
end

BookReview/app/models/review.rb
class Review < ApplicationRecord
end

BookReview/app/models/user.rb
class User < ApplicationRecord
  has_many :books
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

BookReview/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

BookReview/app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :find_book, only: [:edit, :update, :destroy]

    def index
      if params[:category].blank?
        @book = Book.all.order("created_at DESC")
      else
        @category_id = Category.find_by(name: params[:category]).id
        @book = Book.where(category_id: @category_id).order("created_at DESC")
      end
    end

    def show
      @book = Book.find(params[:id])
    end

    def new
      @book = current_user.books.build
      @categories = Category.all.map{ |c| [c.name, c.id] }
    end 

    def create
      @book = current_user.books.build(book_params)
      @book.category_id = params[:category_id]

      if @book.save
        redirect_to root_path
      else
        render 'new'
      end
    end

    def edit
      @categories = Category.all.map{ |c| [c.name, c.id] }
    end

    def update
      if @book.update(book_params)
        redirect_to book_path(@book)
      else
        render 'edit'
      end
    end

    def destroy
      @book.destroy
      redirect_to root_path
    end

    private
      def book_params
        params.require(:book).permit(:title, :description, :author, :category_id)
      end

      def find_book
        @book = Book.find(params[:id])
      end
end

BookReview/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_book

  def new
    @comment = current_user.comments.new
  end

  def create
    #create a new comment for the book from the current_user
    @comment = Comment.new(comment_params)
    @comment.book_id = @book.id
    @comment.user_id = current_user.id

    if @comment.save

      render turbo_stream: [
        #This is for form reload
        turbo_stream.update('update_form', partial: "comments/form", locals: {book: @book}),
        turbo_stream.append('new_comment', partial: 'comments/comment', locals: { comment: @comment })
      ]
      # redirect_to book_path(@book)
    else
      # flash[:notice] = @comment.errors.full_messages.to_sentence
      render 'new'
    end
  end

  private

    def comment_params
      params
        .require(:comment)
        .permit(:content)
        # .merge(book_id: params[:book_id])
    end

    def find_book
      @book = Book.find(params[:book_id])
    end
end

BookReview/app/helpers/application_helper.rb
module ApplicationHelper
end

BookReview/app/helpers/books_helper.rb
module BooksHelper
end

BookReview/app/helpers/comments_helper.rb
module CommentsHelper
end

BookReview/app/views/books/_form.html.erb
<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
    <%= f.input :title, label: "Book Title" %>
    <%= f.input :description %>
    <%= f.input :author %>
    <%= f.button :submit %>
<% end %>

BookReview/app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
    <%= f.select :category_id, @categories %>
    <%= f.input :title, label: "Book Title" %>
    <%= f.input :description %>
    <%= f.input :author %>
    <%= f.button :submit %>
<% end %>

BookReview/app/views/books/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @book.count==0 %>
    <h3>There are no books currently in this category</h3>
<% else %>
    <% @book.each do |book| %>
        <h2><%= link_to book.title, book_path(book) %></h2>
    <% end %>
<% end %>

BookReview/app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %> 

BookReview/app/views/books/show.html.erb
<h2><%= @book.title %></h2>
<h3><%= @book.author %></h3>
<h4>Category: <%= @book.category.name %></h4>
<p><%= @book.description %></p>

<br>
<% if user_signed_in? %>
  <p>
    <strong>Comments:</strong> 
    
    <div id="update_form">
      <%= turbo_frame_tag "form1" do %>
        <button class="button button1"><%= link_to "Add comments", new_book_comment_path(@book) %></button>
      <% end %> 
    </div> 
    <br>
    <div id="new_comment">
      <%= render @book.comments.order(id: :desc) %>
    </div>
  </p>

  <%= link_to "Back", root_path %>

  <% if @book.user_id == current_user.id %>
    
    <%= link_to "Edit", edit_book_path(@book) %>
    <%= link_to "Delete", book_path(@book), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
  <% end %>
  
<% end %>

BookReview/app/views/comments/_comment.html.erb
<article>
  <p><%= comment.content %></p>
  <small>by <%= comment.user.email %></small>
</article>
<hr />

BookReview/app/views/comments/_form.html.erb
<%= simple_form_for ([@book, @book.comments.build]) do |f| %>
  <%= f.input :content, label: "Write your comment" %>
  <%= f.button :submit %>
<% end %> 

BookReview/app/views/comments/new.html.erb
<div>
  <h4>Add Comment</h4>
  <%= turbo_frame_tag "form1" do%>
    <%= render 'form' %>
  <% end %>
</div>

<%
=begin%>
<div id="update_form">  
  <div>
      <%= turbo_frame_tag "frame1" do %>
        <%= render 'form', locals: {book: @book} %>
      <% end %>
  </div>
</div>   
<%
=end%>

BookReview/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <nav class="navbar navbar-default">

      <div class="container">

        <div class="navbar-header">
          <%= link_to "Book Review", root_path, class: "navbar-brand" %>
        </div>

        <ul class="nav navbar-nav">
          <li><%= link_to "Sign Up",  new_user_registration_path %></li>

          <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, data:{ turbo_method: :delete } %></li>
          <% else %>
            <li><%= link_to "Log In", new_user_session_path %></li> 
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">

          <li class="nav-item">
            <% Category.all.each do |category| %>
                    <li>
                      <%= link_to category.name, books_path(category: category.name), class:"link" %>
                    </li>
                  <% end %>
          </li>
          
          
          <% if user_signed_in? %>
            <li><%= link_to "Add Book", new_book_path %>
          <% end %>
        </ul>

      </div>

    </nav>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>