ProductAplication/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :products
end

ProductAplication/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ProductAplication/app/models/brand.rb
class Brand < ApplicationRecord
  belongs_to :product
end

ProductAplication/app/models/product.rb
class Product < ApplicationRecord
  has_one :brand

  scope :price_limit, -> { where ("price < 30000") }

  accepts_nested_attributes_for :brand
end

ProductAplication/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ProductAplication/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show]

  def index
    # @products = Product.price_limit
    # debugger
    # @products = Product.price_limit.includes(:brand)
    # @products = Product.includes(:brand).references(:brand).where('brands.brand_name = ?', 'Google')
    @products = Product.price_limit.eager_load(:brand)

  end

  def new
      @product = Product.new
      @product.build_brand
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product was created successfully!"
      redirect_to product_path(@product)     
    else
      render 'new'
    end
  end

  def show
  
  end

  private
  
    def product_params
      params.require(:product).permit(:name, :price, brand_attributes: [:brand_name])
    end

    def find_product
      @product = Product.find(params[:id])
    end

end

ProductAplication/app/helpers/application_helper.rb
module ApplicationHelper
end

ProductAplication/app/helpers/products_helper.rb
module ProductsHelper
end

ProductAplication/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductAplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

ProductAplication/app/views/products/_form.html.erb
<%
=begin%>
 <%= simple_form_for @product do |f| %>
  <%= f.input :name, label: "Product Name" %>
  <%= f.input :price, label: "Price" %>
  <%= f.button :submit %>
<% end %>  
<%
=end%>

<% if @product.errors.any? %>
  <h2>The following errors prevented the todo from being saved</h2>
  <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>  
  </ul>
<% end %>

<%= form_for @product do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
   <%= f.label :price %>
   <%= f.text_field :price %> 
  </p>

    <%= f.fields_for :brand do |brand_attribute| %>
      <p>
        <%= brand_attribute.label :brand_name, "Brand name" %>
        <%= brand_attribute.text_field :brand_name %>
      </p>
    <% end %>
  <p>
    <%= f.submit %>
  </p>
<% end %>


<%= link_to "Back to product list", products_path %>

ProductAplication/app/views/products/index.html.erb
<h1> Welcome to Product Application</h2>

<p>
  <%= link_to "Create a Product", new_product_path %>
</p>

<table>
  <tr>
    <th>Name</th>
    <th>Price<th>
    <th>Brand Name<th>
  </tr>

  <% @products.each do |p| %>
    <tr>
      <td><%= p.name %></td>
      <td><%= p.price %></td>
      <%
=begin%>
 <% debugger %> 
<%
=end%>
      <td><%= p.brand.brand_name %></td>
    </tr>
  <% end %>
</table>

ProductAplication/app/views/products/new.html.erb
<h4>Add Product</h4>
<%= render 'form' %>

ProductAplication/app/views/products/show.html.erb
<h2> List of products</h2>
<h4><%= @product.name %></h4>
<h4><%= @product.price %></h4>
<h4><%= @product.brand.brand_name %></h4>

<%= link_to "Back to product list", products_path %>