blog/config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  devise_for :users
  resources :articles 
  
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

blog/app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: {minimum: 10}
end

blog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @articles = Article.new
  end

  def create
    @articles = Article.new(article_params)
    
    if @articles.save
      # redirect_to @articles
      flash[:notice] = "Article saved successfully!"
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity 
    end
  end

  def show

  end

  def edit
                                    
  end

  def update
    if @articles.update(article_params)
      flash[:notice] = "Article #{@articles.id} updated successfully!!"
      redirect_to articles_path, status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @articles.destroy
    flash[:notice] = "Article #{@articles.id} deleted successfully."
    redirect_to articles_path, status: :see_other
  end
  

  private
    def set_article
      @articles = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body)
    end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/views/articles/_form.html.erb
<% if @articles.errors.any? %>
  <h2>The following errors prevented the todo from being saved</h2>
  <ul>
    <% @articles.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>  
  </ul>
<% end %>

<%= form_for @articles do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </p>

  <p>
    <%= f.button :submit %>
  </p>
<% end %>

blog/app/views/articles/edit.html.erb
<div>
  <h2>Update the Article</h2>
  <%= turbo_frame_tag "frame1" do %>
    <%= render 'form' %>
    <button type="button"><%= link_to 'Back', articles_path %></p> 
  <% end %>
</div>

blog/app/views/articles/index.html.erb
<h1 style="text-align:center"><b>Articles</b></h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Action</th>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.title, article %></td>
        <td><%= link_to article.body, article %></td>

        <% if user_signed_in? %>
          <td>
            <%= turbo_frame_tag "frame1" do %>
              <button class="button button1"><%= link_to "Edit", edit_article_path(article) %></button>
            <% end %>

          </td>  
          <td>
            <button class="button button2">
              <%= link_to "Delete", article_path(article), data: {turbo_method: :Delete, turbo_confirm: "Are you sure?"} %>
            </button>
          </td> 
        <% end %>
      </tr>
    <% end %>
  </tr>
</table>

blog/app/views/articles/new.html.erb
<h1>Create new Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

blog/app/views/articles/show.html.erb
<h1>Articles</h1>

<h2><%= @articles.title %></h2>
<h3><%= @articles.body %></h3>

<%= link_to "Back", articles_path %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>    
    <nav class="navbar navbar-default">

      <div class="container">

        <div class="navbar-header">
          <%= link_to "Blog Application", root_path, class: "navbar-brand" %>
        </div>

        <ul class="nav navbar-nav">
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :Delete} %></li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
        </ul>

        <ul class="nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Add Articles", new_article_path %></li>
          <% end %>
        
        </ul>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>